// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIOrNjNUgucJHH6_DOjEUR9aP_c-G7zk',
    appId: '1:191367921851:web:7ba8e7e761321518d3a99e',
    messagingSenderId: '191367921851',
    projectId: 'new-project-app-adis',
    authDomain: 'new-project-app-adis.firebaseapp.com',
    storageBucket: 'new-project-app-adis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4sUrBT_KKdzU0AHBBso_QjcfsPWZeu7Q',
    appId: '1:191367921851:android:e55726195e56c06bd3a99e',
    messagingSenderId: '191367921851',
    projectId: 'new-project-app-adis',
    storageBucket: 'new-project-app-adis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksldDXKBOlBCYNVgI7ojOLT2I3HQ2uo0',
    appId: '1:191367921851:ios:4b95248f77471930d3a99e',
    messagingSenderId: '191367921851',
    projectId: 'new-project-app-adis',
    storageBucket: 'new-project-app-adis.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAksldDXKBOlBCYNVgI7ojOLT2I3HQ2uo0',
    appId: '1:191367921851:ios:4b95248f77471930d3a99e',
    messagingSenderId: '191367921851',
    projectId: 'new-project-app-adis',
    storageBucket: 'new-project-app-adis.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxIOrNjNUgucJHH6_DOjEUR9aP_c-G7zk',
    appId: '1:191367921851:web:4b1a019abc2a897dd3a99e',
    messagingSenderId: '191367921851',
    projectId: 'new-project-app-adis',
    authDomain: 'new-project-app-adis.firebaseapp.com',
    storageBucket: 'new-project-app-adis.firebasestorage.app',
  );
}
